"""add Flashcard model

Revision ID: 8cea7197713e
Revises: 
Create Date: 2023-08-23 07:19:02.641660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cea7197713e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard',
    sa.Column('flashcard_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('flashcard_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flashcard')
    # ### end Alembic commands ###
